  version: '3.8'
  services:
    minecraft-server:
      build: .
      ports:
        - "25565:25565"
      volumes:
        - ./minecraft-data:/data
      networks:
        - minecraft-network
      restart: always
      container_name: minecraft-server-1.21.4
    rcon:
      image: outdead/rcon:latest
      command: /bin/sh -c "tail -f README.md"
      networks:
        - minecraft-network
      restart: always
      container_name: rcon-minecraft
  networks:
    minecraft-network:
      driver: bridge
